-- Add items to existing profiles or create your own to sell groups of items using alias commands

local profiles = {}



-- //sellnpc powder

profiles['powder'] = S{

    'prize powder',

    }



-- //sellnpc ore

profiles['ore'] = S{

    'iron ore',

    'copper ore',

    'tin ore',

    }



-- //sellnpc junk

profiles['junk'] = S{

	'acorn',
	'adoulinian kelp',
	'arrowwood log',
	'Acheron Shield',
	'ash log',
	'auric sand',
	'bag of vegetable seeds',
	'barnacle',
	'bat fang',
	'bay leaves',
	'beetle jaw',
	'bhefhel marlin',
	'black eel',
	'black ghost',
	'black pepper',
	'black prawn',
	'bloodblotch',
	'blue peas',
	'bluetail',
	'bone chip',
	'brass loach',
	'ca cuong',
	'carnation',
	'chestnut log',
	'chicken bone',
	'cone calamary',
	'contortopus',
	'copper frog',
	'coral fungus',
	'crab Shell',
	--'crayfish',
	'crescent fish',
	'dark bass',
	'deathball',
	'dogwood log',
	'dragon bone',
	'dwarf remora',
	'eggplant',
	'el. pachira fruit',
	'elm log',
	'elshimo newt',
	'faded crystal',
	'faerie apple',
	'felicifruit',
	'fish bones',
	'flax flower',
	'flint caviar',
	'fresh marjoram',
	'fresh mugwort',
	'fruit seeds',
	'gavial fish',
	'giant catfish',
	--'gigant squid',
	'gold carp',
	'grain seeds',
	'grimmonite',
	--'gugru tuna',
	'habaneros',
	'high-quality scorpion shell';
	'high-quality crab shell';
	'holy basil',
	'igneous rock',
	'insect wing',
	'kazham peppers',
	'king locust',
	'king truffle',
	'land crab meat',
	'lesser chigoe',
	'locust elutriator',
	'mackerel',
	'mahogany log',
	'maple log',
	'mhaura garlic',
	'moko grass',
	'moorish idol',
	'mushroom locust',
	'mushroom saute',
	'napa',
	'pamama au lait',
	'pamamas',
	'pebble',
	'pine nuts',
	'pine nuts',
	'pipira',
	'popoto',
	'prize powder',
	'puffball',
	'pugil scales',
	--'quus',
	'red rose',
	--'red terrapin',
	'rolanberry',
	'ronfaure chestnut',
	'rusty bucket',
	'sage',
	'scorpion shell',
	'scorpion claw',
	'skull locust',
	'semolina',
	'senroh sardine',
	--'shall shell',
	'sheep tooth',
	'snapping mole',
	'snapping mole',
	--'sunflower seeds',
	'titanictus',
	'three-eyed fish',
	'tree Cuttings',
	'ulbukan lobster',
	'urunday log',
	'vanilla',
	'walnut log',
	'walnut',
	'watermelon',
	'water lily',
	'wijnruit',
	'win. tea leaves',
	'woozyshroom',
	'yagudo cherry',
	'yayinbaligi',
	'zebra eel',
	'Two-leaf Mandragora Bud',
	'Land Crab Meat',
	'Carrier Crab Crpc.',
	'H.Q. Crab Shell',
	}

-- //sellnpc junk

profiles['default'] = S{

	'acorn',
	'adoulinian kelp',
	'arrowwood log',
	'Acheron Shield',
	'ash log',
	'auric sand',
	'bag of vegetable seeds',
	'barnacle',
	'bat fang',
	'bay leaves',
	'beetle jaw',
	'bhefhel marlin',
	'black eel',
	'black ghost',
	'black pepper',
	'black prawn',
	'bloodblotch',
	'blue peas',
	'bluetail',
	'bone chip',
	'brass loach',
	'ca cuong',
	'carnation',
	'chestnut log',
	'chicken bone',
	'cone calamary',
	'contortopus',
	'copper frog',
	'coral fungus',
	'crab Shell',
	--'crayfish',
	'crescent fish',
	'dark bass',
	'deathball',
	'dogwood log',
	'dragon bone',
	'dwarf remora',
	'eggplant',
	'el. pachira fruit',
	'elm log',
	'elshimo newt',
	'faded crystal',
	'faerie apple',
	'felicifruit',
	'fish bones',
	'flax flower',
	'flint caviar',
	'fresh marjoram',
	'fresh mugwort',
	'fruit seeds',
	'gavial fish',
	'giant catfish',
	--'gigant squid',
	'gold carp',
	'grain seeds',
	'grimmonite',
	--'gugru tuna',
	'habaneros',
	'high-quality scorpion shell',
	'high-quality crab shell',
	'holy basil',
	'igneous rock',
	'insect wing',
	'kazham peppers',
	'king locust',
	'king truffle',
	'land crab meat',
	'lesser chigoe',
	'locust elutriator',
	'mackerel',
	'mahogany log',
	'maple log',
	'mhaura garlic',
	'moko grass',
	'moorish idol',
	'mushroom locust',
	'mushroom saute',
	'napa',
	'pamama au lait',
	'pamamas',
	'pebble',
	'pine nuts',
	'pine nuts',
	'pipira',
	'popoto',
	'prize powder',
	'puffball',
	'pugil scales',
	--'quus',
	'red rose',
	--'red terrapin',
	'rolanberry',
	'ronfaure chestnut',
	'rusty bucket',
	'sage',
	'scorpion shell',
	'scorpion claw',
	'skull locust',
	'semolina',
	'senroh sardine',
	--'shall shell',
	'sheep tooth',
	'snapping mole',
	'snapping mole',
	--'sunflower seeds',
	'titanictus',
	'three-eyed fish',
	'tree Cuttings',
	'ulbukan lobster',
	'urunday log',
	'vanilla',
	'walnut log',
	'walnut',
	'watermelon',
	'water lily',
	'wijnruit',
	'win. tea leaves',
	'woozyshroom',
	'yagudo cherry',
	'yayinbaligi',
	'zebra eel',
	'two-leaf mandragora bud',
	'carrier crab crpc.',
	'h.q. crab shell',
	}

return profiles